### ISSUE TITLE
demo error: dyld: Library not loaded:

### ISSUE THREAD

**Issue by baxiang** [RTCat/rtcat_ios_demo_1v1#1]
Referenced from: /private/var/mobile/Containers/Bundle/Application/666A3257-4713-4E8F-B7A0-648CAA36F7C2/RTCatDemo1v1.app/RTCatDemo1v1
  Reason: image not found
 RTCatSDK下载地址： https://cdn.realtimecat.com/realtimecat/rtc-ios-sdk-0.1.zip
是否可以提供一下Demo使用的RTCatSDK.framework

**Comment by martianyi** [comment]
http://docs.shishimao.com/05.%20ios/01.%20introduction.html

从 https://cdn.realtimecat.com/realtimecat/rtc-ios-sdk-0.1.zip 下载0.1版的sdk，使用xcode导入。

**Comment by baxiang** [comment]
是的 我是按照这个做的 在xcode7.3和xcode8 都是不可以的 。个人建议可不可以在github的demo 代码直接嵌入sdk或者采用cocoapod的方式。

**Comment by baxiang** [comment]
![816a67d3-81c6-4de5-984d-19e102e3034a](https://cloud.githubusercontent.com/assets/2994323/19261135/a330391e-8fc1-11e6-9802-8f4365544ef1.png)
使用的动态库 需要在使用的时候需要额外加一个步骤,要把Framework同时添加到‘Embedded Binaries’中
Link binary with libraries Link frameworks and libraries with your project’s object files to produce a binary file. You can link a target’s source files against libraries in the target’s active SDK or against external libraries.
Embed Frameworks You can create an embedded framework to share code between your app extension and its containing app.
Timeline If your containing app target links to an embedded framework, it must include the arm64 architecture or it will be rejected by the App Store.
[http://stackoverflow.com/questions/32375687/what-is-the-difference-between-embedded-binaries-and-linked-frameworks](url)
